import type { Metadata } from "next"

import { RQProvider } from "@/config/react-query"
import { geistMono, geistSans } from "@/lib/fonts"
import { Toaster } from "@/components/ui/sonner"
import { ThemeProvider } from "@/components/theme-provider"

import "./globals.css"

import { ModeToggle } from "@/components/toggle-mode"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <ModeToggle />
          <RQProvider>{children}</RQProvider>
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  )
}
